entity_types = {
    "founder": "PERSON",
    "owner": "PERSON",
    "editor": "PERSON",
    "author": "PERSON",
    "producer": "PERSON",
    "writer": "PERSON",
    "cafes": "GPE",
    "location": "GPE",
    "city": "GPE",
    "country": "GPE",
    "state": "GPE",
    "county": "GPE",
    "opened": "DATE",
    "established": "DATE",
    "founded": "DATE",
    "started": "DATE",
    "closed": "DATE",
    "when": "DATE",
    "where": "GPE",
    "cost": "MONEY",
    "price": "MONEY",
    "money": "MONEY",
    "price range": "MONEY",
    "area": "GPE",
    "time": "TIME",
    "starting": "TIME",
}

keyword_values = {
    "what is",
    "code",
    "markup",
    "meetup",
    "event",
    "review",
    "recipe",
    "what are",
    "what were",
    "why",
    "how",
    "microformats",
    "who is",
}
